apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-demo-0
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "~/playground/k8s/data_space/pv-volume-demo"
