apiVersion: batch/v1
kind: Job
metadata:
  name: job-wq-1
spec:
  completions: 9
  parallelism: 2
  template:
    metadata:
      name: job-wq-1
    spec:
      containers:
      - name: c
        image: kmiku7/job-wq-1:0.2
        env:
        - name: BROKER_URL
          value: amqp://guest:guest@rabbitmq-service:5672
        - name: QUEUE
          value: job1
      restartPolicy: OnFailure
