apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-demo
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"  # Here must mask the number with double quotation masks.
  ui_properties_file_name: "user-interface.properties"
  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
