apiVersion: apps/v1           #
kind: Deployment              #
metadata:                     #
  name: nginx-deployment      #
  namespace: test-ns
  labels:                     #
    app: nginx                #
spec:                         #
  replicas: 3                 #--. 相当于 ReplicaSet 的定义
  selector:                   #  |
    matchLabels:              #  |
      app: nginx              #--'
  template:                   #--. 相当于单个 pod 的定义
    metadata:                 #  |
      labels:                 #  |
        app: nginx            #  |
    spec:                     #  |
      containers:             #  |
      - name: nginx           #  |
        image: nginx:1.14.2   #  |
        ports:                #  |
        - containerPort: 80   #--'
        env:
          - name: PLAYER_INITIAL_LIVES
            valueFrom:
              configMapKeyRef:  # Use config item in container.
                name: cm-demo
                key: player_initial_lives
          - name: UI_PROPERTIES_FILE_NAME
            valueFrom:
              configMapKeyRef:
                name: cm-demo
                key: ui_properties_file_name
      volumes:
        - name: config  # Load ConfigMap for Pod.
          configMap:
            name: cm-demo
