apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: test-env
spec:
  selector:
    matchLabels:
      app: nginx-pod
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.5
        ports:
        - containerPort: 80
