# Need to create the directories in the worker node.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ms-volume-demo-0
  labels:
    type: local
    service: mysql-stateful
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/lingang/playground/k8s/data_space/pv-volume-demo-0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ms-volume-demo-1
  labels:
    type: local
    service: mysql-stateful
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/lingang/playground/k8s/data_space/pv-volume-demo-1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ms-volume-demo-2
  labels:
    type: local
    service: mysql-stateful
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/lingang/playground/k8s/data_space/pv-volume-demo-2"
